-- Seed: Services
INSERT INTO services (slug, title_en, title_ro, description_en, description_ro, icon_name, sort_order) VALUES
('web-design', 'Website Design & Development', 'Design și Dezvoltare Web', 'High-performance, beautifully crafted websites that convert visitors into clients.', 'Site-uri web performante, frumos create, care convertesc vizitatorii în clienți.', 'MonitorSmartphone', 1),
('booking-systems', 'Booking & Client Management', 'Sisteme de Rezervări', 'Streamlined scheduling systems that eliminate administrative overhead.', 'Sisteme de programare optimizate care elimină munca administrativă.', 'CalendarCheck', 2),
('automations', 'Lead Capture & Workflow Automation', 'Automatizări & Captare Lead-uri', 'Automated funnels and data syncing to capture every opportunity.', 'Pâlnii automate și sincronizare de date pentru a capta orice oportunitate.', 'Workflow', 3),
('mobile-apps', 'Mobile App Development', 'Dezvoltare Aplicații Mobile', 'Custom iOS and Android solutions for deeper client engagement.', 'Soluții personalizate iOS și Android pentru o implicare mai profundă a clienților.', 'Smartphone', 4);

-- Seed: Pricing Packages
INSERT INTO pricing_packages (title_en, title_ro, price_monthly, description_en, description_ro, features_en, features_ro, is_popular, cta_text_en, cta_text_ro, cta_link, sort_order) VALUES
('Starter', 'Începător', '€499', 'Perfect for new businesses needing a professional digital presence.', 'Perfect pentru afaceri noi care au nevoie de o prezență digitală profesională.', '["Custom 5-page website", "Basic SEO setup", "Contact form integration", "Mobile responsive"]'::jsonb, '["Site web personalizat 5 pagini", "Configurare SEO de bază", "Formular contact integrat", "Optimizat pentru mobil"]'::jsonb, false, 'Get Started', 'Începe acum', '/contact', 1),
('Growth', 'Creștere', '€999', 'For established businesses looking to automate and scale.', 'Pentru afaceri stabile care doresc să automatizeze și să crească.', '["Advanced booking system", "Automated email workflows", "CRM integration", "Monthly analytics"]'::jsonb, '["Sistem avansat de rezervări", "Fluxuri automate de email", "Integrare CRM", "Analize lunare"]'::jsonb, true, 'Get Started', 'Începe acum', '/contact', 2),
('Enterprise', 'Personalizat', 'Custom', 'Custom architecture and complex integrations.', 'Arhitectură personalizată și integrări complexe.', '["Dedicated mobile app", "Custom API integrations", "Priority 24/7 support", "Dedicated account manager"]'::jsonb, '["Aplicație mobilă dedicată", "Integrări API personalizate", "Suport prioritar 24/7", "Manager de cont dedicat"]'::jsonb, false, 'Contact Us', 'Contactează-ne', '/contact', 3);

-- Seed: Work Items
INSERT INTO work_items (slug, title_en, title_ro, client_name, industry_en, industry_ro, description_en, description_ro, image_url, stats, is_featured, sort_order) VALUES
('luxe-salon', 'Luxe Beauty Salon', 'Salonul de Înfrumusețare Luxe', 'Luxe Beauty', 'Salons', 'Saloane', 'A complete digital transformation including a custom booking portal that increased appointments by 40%.', 'O transformare digitală completă incluzând un portal de rezervări care a crescut programările cu 40%.', '/placeholder-salon.jpg', '[{"label": "Bookings", "value": "+40%"}, {"label": "Admin Time", "value": "-15h/wk"}]'::jsonb, true, 1),
('medica-clinic', 'Medica Health Clinic', 'Clinica Medica', 'Medica Health', 'Clinics', 'Clinici', 'Secure patient onboarding and automated reminder pipelines reducing no-shows entirely.', 'Sistem securizat de înregistrare pacienți și mementouri automate care au redus complet neprezentările.', '/placeholder-clinic.jpg', '[{"label": "No-shows", "value": "-95%"}, {"label": "Retention", "value": "+22%"}]'::jsonb, true, 2);

-- Seed: FAQs
INSERT INTO faqs (question_en, question_ro, answer_en, answer_ro, category_en, category_ro, sort_order) VALUES
('How long does a typical project take?', 'Cât durează un proiect tipic?', 'Most growth packages are implemented within 4 to 6 weeks, depending on the complexity of your workflow integrations.', 'Majoritatea pachetelor de creștere sunt implementate în 4 până la 6 săptămâni, în funcție de complexitate.', 'General', 'General', 1),
('Do I need technical skills to manage my new system?', 'Am nevoie de abilități tehnice pentru a gestiona noul sistem?', 'Not at all. We build tools that are intuitive for your entire team, and we provide complete training before hand-off.', 'Deloc. Construim instrumente intuitive pentru întreaga echipă și oferim instruire completă la predare.', 'Support', 'Suport', 2);
